# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class DnsToMdns < Formula
  service do
    run [opt_bin/"dns-to-mdns", "-p", "8053"]
    keep_alive true
    working_dir HOMEBREW_PREFIX
    log_path var/"log/dns-to-mdns.log"
    error_log_path var/"log/dns-to-mdns-error.log"
  end

  desc "Start a dns server and convert request to mdns dns request"
  homepage "https://github.com/blackhuman/dns-to-mdns"
  url "https://github.com/blackhuman/dns-to-mdns/releases/download/v0.1.2/dns-to-mdns-0.1.2-darwin-universal.tar.gz"
  sha256 "1e06b1b2253083e5436760d24e22becd826e2626181ecc80b5cd387629e28975"

  depends_on macos: :monterey

  def install
    bin.install "dns-to-mdns"
  end

  test do
    system "#{bin}/dns-to-mdns", "--help"
  end
end
