# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class DnsToMdns < Formula
  service do
    run [opt_bin/"dns-to-mdns", "-p", "8053"]
    keep_alive true
    working_dir HOMEBREW_PREFIX
    log_path var/"log/dns-to-mdns.log"
    error_log_path var/"log/dns-to-mdns-error.log"
  end

  desc "Start a dns server and convert request to mdns dns request"
  homepage "https://github.com/blackhuman/dns-to-mdns"
  url "https://github.com/blackhuman/dns-to-mdns/releases/download/v0.1.1/dns-to-mdns-0.1.1-darwin-universal.tar.gz"
  sha256 "f50cd14b2d0854c0267dd5897666309ce63953c175abbf0b0de51bbbe78d4ba4"

  depends_on macos: :monterey

  def install
    bin.install "dns-to-mdns"
  end

  test do
    system "#{bin}/dns-to-mdns", "--help"
  end
end
